const fs = require('fs')

async function getPropertiesFile() {
    let result = await fetch('https://raw.githubusercontent.com/Cyberghxst/bdjs/v1/autogenerated/properties/PROPERTIES.md')
    if (!result.ok) result = await fetch('https://raw.githubusercontent.com/Cyberghxst/bdjs/v1/autogenerated/PROPERTIES.md')
    if (!result.ok) throw new Error('Cannot fetch properties file!')
    fs.writeFileSync('./docs/guides/properties.md', await result.text())
}

module.exports = { getPropertiesFile }